import { z } from "zod";

/**
 * Pipeline-computed extraction metadata for caching and tracking parse quality.
 * Note: Computed deterministically by pipeline code, not generated by an LLM prompt.
 */
export const ExtractionMetadataSchema = z.object({
  file_hash: z
    .string()
    .describe("Content hash of the uploaded resume document for cache keying"),
  schema_version: z
    .string()
    .describe("Version tag of the extraction schema to trigger re-extraction only when affected"),
  parse_quality: z
    .enum(["full", "partial", "failed"])
    .describe("full (clean parse), partial (some sections unparseable), failed (OCR/corrupt scan failure)"),
  raw_text_ref: z
    .string()
    .describe("Pointer or key to original extracted raw text for fallback single-field queries"),
});

export type ExtractionMetadata = z.infer<typeof ExtractionMetadataSchema>;

export const extractionMetadataAspect = {
  name: "extraction_metadata",
  schema: ExtractionMetadataSchema,
  isPromptDriven: false,
} as const;
