import type { FormFieldState } from "@/features/jobs/types";
import { CANONICAL_SKILLS } from "@/features/extraction/skillNormalizer";
import { CANONICAL_FIELDS_OF_STUDY } from "@/features/extraction/fieldOfStudyNormalizer";

export const initialRequirementsFields: Record<string, FormFieldState> = {
  minExperience: {
    id: "minExperience",
    label: "Minimum Experience",
    helperText: "Minimum years of general professional experience",
    mode: "hard",
    value: 4,
    unit: "years",
    active: true,
  },
  skillsRequired: {
    id: "skillsRequired",
    label: "Mandatory Skills (Dealbreaker)",
    helperText: "Select canonical must-have skills that are hard dealbreakers if missing",
    mode: "hard",
    value: "TypeScript, React, Node.js",
    options: CANONICAL_SKILLS,
    active: true,
  },
  skillsPreferred: {
    id: "skillsPreferred",
    label: "Preferred Skills (Bonus)",
    helperText: "Select canonical nice-to-have skills scored for bonus qualification",
    mode: "soft",
    value: "Next.js, Tailwind CSS, PostgreSQL",
    options: CANONICAL_SKILLS,
    active: true,
  },
  degreeLevel: {
    id: "degreeLevel",
    label: "Minimum Degree Level",
    helperText: "Standardized degree tier required (toggle to Hard for strict dealbreaker)",
    mode: "hard",
    value: "bachelors",
    options: ["none", "high_school", "diploma", "bachelors", "masters", "doctorate"],
    active: true,
  },
  fieldOfStudy: {
    id: "fieldOfStudy",
    label: "Field of Study",
    helperText: "Canonical academic discipline or major from closed set",
    mode: "soft",
    value: "Computer Science",
    options: CANONICAL_FIELDS_OF_STUDY,
    active: true,
  },
  locationCity: {
    id: "locationCity",
    label: "City Requirement",
    helperText: "Canonical city boundary required for physical or jurisdiction match",
    mode: "hard",
    value: "Lahore",
    options: [
      "Any",
      "Lahore",
      "Karachi",
      "Islamabad",
      "Rawalpindi",
      "Faisalabad",
      "Multan",
      "Peshawar",
      "Quetta",
      "Sialkot",
      "Gujranwala",
      "Hyderabad",
      "Abbottabad",
    ],
    active: true,
  },
  locationProvince: {
    id: "locationProvince",
    label: "Province / Region",
    helperText: "Canonical province or state region",
    mode: "hard",
    value: "Punjab",
    options: [
      "Any",
      "Punjab",
      "Sindh",
      "Islamabad Capital Territory",
      "Khyber Pakhtunkhwa",
      "Balochistan",
      "Azad Jammu and Kashmir",
      "Gilgit-Baltistan",
    ],
    active: true,
  },
  workMode: {
    id: "workMode",
    label: "Workplace Mode",
    helperText: "Physical attendance requirement: onsite, hybrid, or remote",
    mode: "hard",
    value: "hybrid",
    options: ["onsite", "hybrid", "remote"],
    active: true,
  },
  compensationMin: {
    id: "compensationMin",
    label: "Minimum Compensation Floor",
    helperText: "Starting base compensation floor",
    mode: "soft",
    value: 400000,
    active: true,
  },
  compensationMax: {
    id: "compensationMax",
    label: "Maximum Compensation Ceiling",
    helperText: "Maximum allocated budget for candidate base salary",
    mode: "hard",
    value: 600000,
    active: true,
  },
  compensationCurrency: {
    id: "compensationCurrency",
    label: "Compensation Currency",
    helperText: "Currency unit for compensation band",
    mode: "soft",
    value: "PKR",
    options: ["PKR", "USD"],
    active: true,
  },
  noticePeriod: {
    id: "noticePeriod",
    label: "Max Notice Period",
    helperText: "Maximum allowable notice duration before candidate start date",
    mode: "hard",
    value: 30,
    unit: "days",
    active: true,
  },
  noticePeriodUnit: {
    id: "noticePeriodUnit",
    label: "Notice Period Unit",
    helperText: "Time unit for notice period",
    mode: "hard",
    value: "days",
    options: ["days", "weeks", "months"],
    active: true,
  },
};
