// Curated closed set catalog of ~500 canonical technical skills
export const CANONICAL_SKILLS: string[] = [
  ".NET Core",
  ".NET Framework",
  "Active Record",
  "ActiveMQ",
  "Actix Web",
  "AdonisJS",
  "Aerospike",
  "Agile Methodologies",
  "Algolia",
  "Alpine.js",
  "Amazon API Gateway",
  "Amazon Aurora",
  "Amazon CloudFront",
  "Amazon CloudWatch",
  "Amazon DynamoDB",
  "Amazon EC2",
  "Amazon ECS",
  "Amazon EKS",
  "Amazon EventBridge",
  "Amazon Kinesis",
  "Amazon Neptune",
  "Amazon RDS",
  "Amazon Redshift",
  "Amazon Route 53",
  "Amazon S3",
  "Amazon SNS",
  "Amazon SQS",
  "Android Development",
  "Android Studio",
  "Angular",
  "Ansible",
  "Ant Design",
  "Apache Airflow",
  "Apache Beam",
  "Apache Cassandra",
  "Apache Druid",
  "Apache Flink",
  "Apache Hadoop",
  "Apache HBase",
  "Apache Hive",
  "Apache HTTP Server",
  "Apache Hudi",
  "Apache Iceberg",
  "Apache Kafka",
  "Apache Pinot",
  "Apache Pulsar",
  "Apache Solr",
  "Apache Spark",
  "Apex",
  "API Gateway",
  "Apollo Client",
  "Apollo Server",
  "AppDynamics",
  "Application Security",
  "AR/VR",
  "ArangoDB",
  "Arduino",
  "ArgoCD",
  "ARM Architecture",
  "Artificial Intelligence",
  "ASP.NET Core",
  "Assembly",
  "Astro",
  "Asynchronous Programming",
  "Auth0",
  "AWS",
  "AWS Athena",
  "AWS CDK",
  "AWS CloudFormation",
  "AWS Glue",
  "AWS IAM",
  "AWS Lambda",
  "AWS Step Functions",
  "Axum",
  "Azure Active Directory",
  "Azure App Service",
  "Azure Blob Storage",
  "Azure Cosmos DB",
  "Azure DevOps",
  "Azure Event Hubs",
  "Azure Functions",
  "Azure Kubernetes Service (AKS)",
  "Azure Service Bus",
  "Azure SQL Database",
  "Azure Virtual Machines",
  "Babel",
  "Backbone.js",
  "Bamboo",
  "Bash",
  "Behavior-Driven Development (BDD)",
  "BentoML",
  "BFF Pattern",
  "Bitbucket",
  "Bitbucket Pipelines",
  "BLE",
  "Blockchain",
  "Bootstrap",
  "Bulma",
  "Bun",
  "C",
  "C#",
  "C++",
  "Canvas API",
  "CatBoost",
  "Celery",
  "CentOS",
  "Chai",
  "Chakra UI",
  "Chef",
  "Chi",
  "ChromaDB",
  "CI/CD",
  "CircleCI",
  "Clean Architecture",
  "ClickHouse",
  "Clojure",
  "Cloudflare",
  "Cloudflare CDN",
  "CloudFormation",
  "CloudWatch",
  "COBOL",
  "CockroachDB",
  "Code Review",
  "CodeIgniter",
  "Computer Vision",
  "Concurrency & Multithreading",
  "Confluence",
  "Consul",
  "containerd",
  "Cordova",
  "Couchbase",
  "CouchDB",
  "CQRS",
  "Cross-Browser Compatibility",
  "Cryptography",
  "CSS Grid",
  "CSS Modules",
  "CSS3",
  "CUDA",
  "Cybersecurity",
  "Cypress",
  "Dagster",
  "DaisyUI",
  "Dart",
  "Data Governance",
  "Data Lake",
  "Data Modeling",
  "Data Warehousing",
  "Databricks",
  "Datadog",
  "dbt",
  "Debian",
  "Deep Learning",
  "Delta Lake",
  "Deno",
  "Design Patterns",
  "Dgraph",
  "Diesel",
  "DigitalOcean",
  "Distributed Systems",
  "Django",
  "Django REST Framework",
  "DNS",
  "Docker",
  "Docker Compose",
  "DOM Manipulation",
  "Domain-Driven Design (DDD)",
  "Dragonfly",
  "Drizzle ORM",
  "DuckDB",
  "DVC",
  "Dynatrace",
  "E-Commerce",
  "Echo",
  "Elasticsearch",
  "Elixir",
  "ELK Stack",
  "Embedded Systems",
  "Ember.js",
  "Emotion",
  "Encryption",
  "End-to-End (E2E) Testing",
  "Entity Framework Core",
  "Envoy",
  "Erlang",
  "esbuild",
  "Ethereum",
  "Ethers.js",
  "Ethical Hacking",
  "ETL Pipelines",
  "Event Sourcing",
  "Event-Driven Architecture",
  "Expo",
  "Express.js",
  "F#",
  "Faiss",
  "FastAPI",
  "Fastify",
  "Fastlane",
  "Fault Tolerance",
  "Fiber",
  "Fine-Tuning",
  "FinTech",
  "Firebase",
  "Firestore",
  "Flask",
  "Flexbox",
  "Fluent Bit",
  "Fluentd",
  "Flutter",
  "Flux CD",
  "Fly.io",
  "Flyway",
  "Fortran",
  "Framer Motion",
  "FreeRTOS",
  "Functional Programming (FP)",
  "Gatsby",
  "Generative AI",
  "Gin",
  "Git",
  "Git Flow",
  "GitHub",
  "GitHub Actions",
  "GitLab",
  "GitLab CI/CD",
  "Go",
  "Go Test",
  "Godot",
  "Google BigQuery",
  "Google Cloud Build",
  "Google Cloud Functions",
  "Google Cloud IAM",
  "Google Cloud Platform",
  "Google Cloud Pub/Sub",
  "Google Cloud Run",
  "Google Cloud Spanner",
  "Google Cloud SQL",
  "Google Cloud Storage",
  "Google Compute Engine",
  "Google Kubernetes Engine (GKE)",
  "GORM",
  "Grafana",
  "GraphQL",
  "Groovy",
  "gRPC",
  "GSAP",
  "Gulp",
  "Hapi",
  "HAProxy",
  "Hardhat",
  "Haskell",
  "Hasura",
  "Hazelcast",
  "Headless UI",
  "HealthTech",
  "Helm",
  "Heroku",
  "Hetzner",
  "Hibernate",
  "High Availability",
  "HTML5",
  "HTMX",
  "HTTP/2",
  "HTTP/3",
  "Hugging Face",
  "Hyperledger Fabric",
  "IAM",
  "IBM Db2",
  "Image Processing",
  "IndexedDB",
  "Integration Testing",
  "Ionic",
  "iOS Development",
  "IoT",
  "ISO 27001",
  "Istio",
  "Jaeger",
  "JanusGraph",
  "Java",
  "JavaScript",
  "JavaScript (ES6+)",
  "JAX",
  "Jenkins",
  "Jest",
  "Jetpack Compose",
  "Jira",
  "JMeter",
  "Jotai",
  "JPA",
  "jQuery",
  "Julia",
  "JUnit",
  "JVM",
  "JWT",
  "k6",
  "Kanban",
  "Keras",
  "Keycloak",
  "KeyDB",
  "Knex.js",
  "Koa",
  "Kotlin",
  "Kotlin Multiplatform",
  "Kubeflow",
  "Kubernetes",
  "Kustomize",
  "LangChain",
  "Laravel",
  "Large Language Models (LLMs)",
  "Lerna",
  "Less",
  "LightGBM",
  "Linkerd",
  "Linode",
  "Linux",
  "Liquibase",
  "Lit",
  "LlamaIndex",
  "Load Balancing",
  "Load Testing",
  "Locust",
  "Loki",
  "Lua",
  "Machine Learning",
  "macOS",
  "MariaDB",
  "Material UI",
  "MATLAB",
  "Meilisearch",
  "Memcached",
  "Microcontrollers",
  "Micronaut",
  "Microsoft Azure",
  "Microsoft SQL Server",
  "Milvus",
  "MLflow",
  "MobX",
  "Mocha",
  "Mockito",
  "MongoDB",
  "Mongoose",
  "Monolithic Architecture",
  "MQTT",
  "MyBatis",
  "MySQL",
  "NATS",
  "Natural Language Processing (NLP)",
  "Neo4j",
  "NestJS",
  "Netlify",
  "Network Security",
  "New Relic",
  "Newman",
  "Next.js",
  "Nginx",
  "NgRx",
  "Nim",
  "NLTK",
  "Node.js",
  "Nomad",
  "npm",
  "Nuxt.js",
  "Nx",
  "OAuth 2.0",
  "Object Detection",
  "Object-Oriented Programming (OOP)",
  "Objective-C",
  "OCaml",
  "Okta",
  "ONNX",
  "OpenAPI",
  "OpenCV",
  "OpenID Connect",
  "OpenSearch",
  "OpenShift",
  "OpenTelemetry",
  "Oracle Database",
  "OWASP Top 10",
  "Packer",
  "Parcel",
  "Penetration Testing",
  "Performance Testing",
  "Perl",
  "pgvector",
  "Phoenix",
  "PHP",
  "PHPUnit",
  "Pinecone",
  "Pinia",
  "Playwright",
  "pnpm",
  "Podman",
  "PostCSS",
  "PostgreSQL",
  "Postman",
  "PowerShell",
  "Preact",
  "Prefect",
  "Prisma",
  "Prometheus",
  "Prompt Engineering",
  "Protocol Buffers",
  "Public Key Infrastructure (PKI)",
  "Pulumi",
  "Puppet",
  "Puppeteer",
  "PWA (Progressive Web Apps)",
  "PyTest",
  "Python",
  "PyTorch",
  "Qdrant",
  "Quarkus",
  "Qwik",
  "R",
  "RabbitMQ",
  "Racket",
  "Radix UI",
  "RAG (Retrieval-Augmented Generation)",
  "Railway",
  "Rancher",
  "Raspberry Pi",
  "Ray",
  "React",
  "React Context API",
  "React Native",
  "React Testing Library",
  "Recoil",
  "Red Hat Enterprise Linux (RHEL)",
  "Redis",
  "Redis Pub/Sub",
  "Redux",
  "Redux Toolkit",
  "Regression Testing",
  "Reinforcement Learning",
  "Relay",
  "Remix",
  "Render",
  "Responsive Web Design",
  "REST API",
  "RethinkDB",
  "Rollup",
  "RSpec",
  "RTOS",
  "Ruby",
  "Ruby on Rails",
  "Rust",
  "RxJS",
  "SaltStack",
  "SAML",
  "SAP HANA",
  "Sass",
  "Scala",
  "Scalability",
  "Scikit-learn",
  "Scrum",
  "SCSS",
  "ScyllaDB",
  "Selenium",
  "Semantic HTML",
  "Semantic UI",
  "Sentry",
  "Sequelize",
  "Serverless Architecture",
  "Service Workers",
  "Shadcn UI",
  "Shell Scripting",
  "Sidekiq",
  "Sinatra",
  "Smart Contracts",
  "Snowflake",
  "SOAP",
  "SOC 2",
  "Solana",
  "SOLID Principles",
  "Solidity",
  "SolidJS",
  "SonarQube",
  "spaCy",
  "Speech Recognition",
  "Spinnaker",
  "Splunk",
  "Spring Boot",
  "Spring Cloud",
  "Spring Security",
  "SQL",
  "SQLAlchemy",
  "SQLite",
  "SSL/TLS",
  "Stable Diffusion",
  "Storybook",
  "Styled Components",
  "Supabase",
  "Svelte",
  "SVG",
  "Swagger",
  "SWC",
  "Swift",
  "SwiftUI",
  "SWR"
];
