import type { GroupNode, GroupEdge } from "./types";

export const INITIAL_GROUPS: GroupNode[] = [
  {
    id: "node-root",
    title: "All Applicants",
    subtitle: "Job Ingress Pipeline Root",
    description: "Root cluster containing all parsed candidate profiles evaluated against senior engineering requirements.",
    badge: "Master Pool",
    status: "active",
    parentId: null,
    childrenIds: ["node-left", "node-right"],
    x: 600,
    y: 90,
    width: 56,
    height: 56,
    candidateCount: 6,
    criteriaDescription: "All candidates submitted for Job Sample 1 (Senior Full Stack Engineer)",
    candidates: [
      {
        id: "cand_hamza",
        name: "Hamza Tariq",
        role: "Senior Full Stack Engineer",
        verifiedYears: 6,
        matchScore: 98,
        status: "knockout_passed",
        highlights: ["TypeScript & Node.js confirmed", "PKR 500k <= 600k budget", "1 mo notice"],
      },
      {
        id: "cand_ayesha",
        name: "Dr. Ayesha Malik",
        role: "Lead Full Stack Architect",
        verifiedYears: 10,
        matchScore: 89,
        status: "review_needed",
        highlights: ["Doctorate in CS", "3 months notice period (negotiation flag)"],
      },
      {
        id: "cand_jillani",
        name: "Muhammad Ghulam Jillani",
        role: "Full Stack Developer",
        verifiedYears: 4,
        matchScore: 82,
        status: "review_needed",
        highlights: ["4y verified vs 5y target", "Strong demonstrated React & TS"],
      },
      {
        id: "cand_abdullah",
        name: "Abdullah Khan",
        role: "Full Stack Engineer",
        verifiedYears: 7,
        matchScore: 78,
        status: "borderline",
        highlights: ["PKR 750k requested vs 600k ceiling", "Excellent architectural portfolio"],
      },
      {
        id: "cand_zainab",
        name: "Zainab Abbas",
        role: "Frontend Developer",
        verifiedYears: 3,
        matchScore: 71,
        status: "review_needed",
        highlights: ["Next.js & React expert", "Node.js declared but lacks backend tenure"],
      },
      {
        id: "cand_bilal",
        name: "Bilal Ahmed",
        role: "Backend Engineer",
        verifiedYears: 5,
        matchScore: 74,
        status: "borderline",
        highlights: ["Islamabad based / remote only", "Relocation reluctant"],
      },
    ],
  },
  {
    id: "node-left",
    title: "Fast-Clear Tier",
    subtitle: "All Knockouts Passed",
    description: "Candidates satisfying all 7 dealbreaker knockouts: min experience, required skills, degree, work mode, and budget.",
    badge: "100% Dealbreaker Fit",
    status: "clear",
    parentId: "node-root",
    childrenIds: ["node-bottom-left"],
    x: 360,
    y: 300,
    width: 56,
    height: 56,
    candidateCount: 2,
    criteriaDescription: "0 blocking violations, demonstrated required skills, verified tenure >= 5 years",
    candidates: [
      {
        id: "cand_hamza",
        name: "Hamza Tariq",
        role: "Senior Full Stack Engineer",
        verifiedYears: 6,
        matchScore: 98,
        status: "knockout_passed",
        highlights: ["Fast-clear hero", "Immediate interview recommendation"],
      },
      {
        id: "cand_ayesha",
        name: "Dr. Ayesha Malik",
        role: "Lead Full Stack Architect",
        verifiedYears: 10,
        matchScore: 89,
        status: "review_needed",
        highlights: ["PhD in Computer Science", "Exceeds all technical bars"],
      },
    ],
  },
  {
    id: "node-bottom-left",
    title: "Immediate Interview",
    subtitle: "Top Priority Candidates",
    description: "Candidates ready for technical round scheduling with zero negotiation or clarification delays.",
    badge: "Priority A",
    status: "clear",
    parentId: "node-left",
    childrenIds: [],
    x: 300,
    y: 530,
    width: 56,
    height: 56,
    candidateCount: 1,
    criteriaDescription: "Immediate availability, within budget ceiling, 6y+ verified history",
    candidates: [
      {
        id: "cand_hamza",
        name: "Hamza Tariq",
        role: "Senior Full Stack Engineer",
        verifiedYears: 6,
        matchScore: 98,
        status: "knockout_passed",
        highlights: ["All 7 blocking checks passed cleanly", "Prompt technical round dispatch"],
      },
    ],
  },
  {
    id: "node-right",
    title: "Review & Edge Cases",
    subtitle: "Qualified with Exceptions",
    description: "Candidates meeting core competence but with one or more flags requiring recruiter discretion or salary negotiation.",
    badge: "2nd Look Required",
    status: "review",
    parentId: "node-root",
    childrenIds: ["node-bottom-mid", "node-bottom-right"],
    x: 880,
    y: 310,
    width: 56,
    height: 56,
    candidateCount: 4,
    criteriaDescription: "Requires manual evaluation of experience gap, notice period, or compensation ask",
    candidates: [
      {
        id: "cand_jillani",
        name: "Muhammad Ghulam Jillani",
        role: "Full Stack Developer",
        verifiedYears: 4,
        matchScore: 82,
        status: "review_needed",
        highlights: ["1 year below stated 5y experience threshold"],
      },
      {
        id: "cand_abdullah",
        name: "Abdullah Khan",
        role: "Full Stack Engineer",
        verifiedYears: 7,
        matchScore: 78,
        status: "borderline",
        highlights: ["Compensation above ceiling by PKR 150k"],
      },
      {
        id: "cand_zainab",
        name: "Zainab Abbas",
        role: "Frontend Developer",
        verifiedYears: 3,
        matchScore: 71,
        status: "review_needed",
        highlights: ["Declared skills need technical screening validation"],
      },
      {
        id: "cand_bilal",
        name: "Bilal Ahmed",
        role: "Backend Engineer",
        verifiedYears: 5,
        matchScore: 74,
        status: "borderline",
        highlights: ["Remote agreement required"],
      },
    ],
  },
  {
    id: "node-bottom-mid",
    title: "Skill Alignment",
    subtitle: "Experience & Tech Gaps",
    description: "Talented engineers who marginally miss hard criteria (e.g. 4 years vs 5 years) but show high-density evidence in work history.",
    badge: "Borderline Tech",
    status: "review",
    parentId: "node-right",
    childrenIds: [],
    x: 740,
    y: 550,
    width: 56,
    height: 56,
    candidateCount: 2,
    criteriaDescription: "Near-match experience or self-reported skills requiring assessment test verification",
    candidates: [
      {
        id: "cand_jillani",
        name: "Muhammad Ghulam Jillani",
        role: "Full Stack Developer",
        verifiedYears: 4,
        matchScore: 82,
        status: "review_needed",
        highlights: ["Fast-tracker with high impact in current role"],
      },
      {
        id: "cand_zainab",
        name: "Zainab Abbas",
        role: "Frontend Developer",
        verifiedYears: 3,
        matchScore: 71,
        status: "review_needed",
        highlights: ["High quality React & Next.js demonstrated portfolio"],
      },
    ],
  },
  {
    id: "node-bottom-right",
    title: "Logistics Negotiation",
    subtitle: "Compensation & Notice Exceptions",
    description: "Senior candidates exceeding technical requirements whose salary expectation or notice duration requires hiring manager sign-off.",
    badge: "Logistics Review",
    status: "hold",
    parentId: "node-right",
    childrenIds: [],
    x: 1260,
    y: 570,
    width: 56,
    height: 56,
    candidateCount: 2,
    criteriaDescription: "Salary > PKR 600,000 or Notice Period > 30 days",
    candidates: [
      {
        id: "cand_abdullah",
        name: "Abdullah Khan",
        role: "Full Stack Engineer",
        verifiedYears: 7,
        matchScore: 78,
        status: "borderline",
        highlights: ["Asks PKR 750,000 (standard band 600k)"],
      },
      {
        id: "cand_bilal",
        name: "Bilal Ahmed",
        role: "Backend Engineer",
        verifiedYears: 5,
        matchScore: 74,
        status: "borderline",
        highlights: ["Requires remote contract exception from Lahore office"],
      },
    ],
  },
];

export const INITIAL_EDGES: GroupEdge[] = [
  {
    id: "edge-root-left",
    sourceId: "node-root",
    targetId: "node-left",
  },
  {
    id: "edge-root-right",
    sourceId: "node-root",
    targetId: "node-right",
  },
  {
    id: "edge-left-bottomleft",
    sourceId: "node-left",
    targetId: "node-bottom-left",
  },
  {
    id: "edge-right-bottommid",
    sourceId: "node-right",
    targetId: "node-bottom-mid",
  },
  {
    id: "edge-right-bottomright",
    sourceId: "node-right",
    targetId: "node-bottom-right",
  },
];
